version: '3.9'

services:
  backend:
    build:
      context: .
      dockerfile: app/dockerfile
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    environment:
      - FLASK_APP=run.py
      - FLASK_ENV=development

  frontend:
    build:
      context: .
      dockerfile: dockerfile.frontend
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    stdin_open: true
    tty: true
